version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Build started on `date`

  build:
    commands:
      - python manage.py makemigrations
      - python manage.py migrate  
      - python manage.py test 
      # Run the tests
      - coverage run manage.py test


  post_build:
    commands:
    # Run pylint on the codebase
    #  - pylint todoApp/
    # Generate code coverage report and fail under 80%
      - coverage report --fail-under=80
      - coverage xml -o coverage.xml
      - echo Build completed on `date`

artifacts:
  files:
    - .ebextensions/**/*
    - coverage.xml